### PR TITLE
Improve wiki pages (DM)

### PR DESCRIPTION
**Pull request by Andre601**
Improved `README.md` and the `item.md` in the options-and-configurations section.

Improvements:
- Made table actually readable.
- Grouped up links at the top of the page for easy updating and changing
- Changed `[text](file.md#text)` to `[text](#text)`
- Removed useless/not needed backslashes from () and []

If for whatever reason the wiki-software you use doesn't support those changes, get a better alternative like [MkDocs](https://mkdocs.org)

### CODE REVIEW

**Comment by aBooDyy** [comment]
Hello there,

Thanks for your interest, but as I can see, none of these changes improve the wiki's user interface. In fact, some of them might break it. I'm not sure about this but wouldn't like to try.
The whole wiki has been rewritten from the GitBook online app, which should explain the syntax of the files.

Thanks for your suggestion, but I don't think we have plans for switching to another wiki software.

**Comment by Andre601** [comment]
Understandably, even tho I think GitBook is trash.

At least fix the typo that this PR also fixed (CommandEvent description) and the broken Markdown in item.md ([Line 27](https://github.com/help-chat/Wiki2/pull/6/files#diff-07274ae320411cf6a4ba93eb76595201R27))

In addition should the requirements have more information. I.e. what options in "has item" are optional and which one are required?

**Comment by aBooDyy** [comment]
> Understandably, even tho I think GitBook is trash.

That's your personal opinion and I do respect that but I think GitBook is good.

> At least fix the typo that this PR also fixed (CommandEvent description) and the broken Markdown in item.md (Line 27)

Thanks for pointing that out! This PR doesn't fix it by the way. Fixed though 👍 
Would you please help me find the "broken markdown" you mentioned? Couldn't find anything wrong [here](https://img.aboodyy.net/20.03.11_16-12.png).

> In addition should the requirements have more information. I.e. what options in "has item" are optional and which one are required?

Sounds nice. I'll look into it later today 👍

**Comment by Andre601** [comment]
I mentioned which line: Line 27.
And the PR did fix the typo (was ad instead of as)

**Comment by aBooDyy** [comment]
> I mentioned which line: Line 27.

Oh yes, line 17 * 👍 

> And the PR did fix the typo (was ad instead of as)

[Doesn't seem like it does.](https://github.com/Andre601/Wiki2/blob/master/clips-plugins/deluxemenus/options-and-configurations/README.md#actions-types)

**Pull request closed without merging**
